name: Site Docker Release

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
        uses: docker/build-push-action@v1.1.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mrrowey/Roweys-FAF-Development-site
          push: ${{ github.ref == 'refs/heads/Develop' || startsWith(github.ref, 'refs/tags') }}
          tag_with_ref: true
